services:
  web1:
    image: nginx:alpine
    container_name: web1
    volumes:
      - ./server1/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - lbnet

  web2:
    image: nginx:alpine
    container_name: web2
    volumes:
      - ./server2/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - lbnet

  loadbalancer:
    image: nginx:alpine
    container_name: loadbalancer
    ports:
      - "8080:80"
    volumes:
      - ./lb/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web1
      - web2
    networks:
      - lbnet

networks:
  lbnet:
    driver: bridge
